#!/bin/bash
# Installs git hooks into .git/hooks/.
# Run this script once to activate automatic GitHub sync on every commit.
# It is also called automatically by scripts/post-merge.sh after each task merge.

HOOKS_DIR=".git/hooks"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ ! -d "$HOOKS_DIR" ]; then
  echo "[setup-git-hooks] .git/hooks directory not found — skipping (not a git repo or CI environment)." >&2
  exit 0
fi

cat > "$HOOKS_DIR/post-commit" << 'EOF'
#!/bin/bash
# Auto-generated by scripts/setup-git-hooks.sh
# Pushes to GitHub after every commit (including Replit checkpoints).

SYNC_LOG="/tmp/github-sync.log"
{
  bash "$(git rev-parse --show-toplevel)/scripts/github-sync.sh"
} >> "$SYNC_LOG" 2>&1 &
EOF

chmod +x "$HOOKS_DIR/post-commit"
echo "[setup-git-hooks] post-commit hook installed at ${HOOKS_DIR}/post-commit"
