#!/bin/bash
# Installs git hooks into .git/hooks/.
# Run this script once to activate automatic GitHub sync on every commit.
# It is also called automatically by scripts/post-merge.sh after each task merge.

set -e

HOOKS_DIR=".git/hooks"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ ! -d "$HOOKS_DIR" ]; then
  echo "[setup-git-hooks] .git/hooks directory not found — are you in the repo root?" >&2
  exit 1
fi

cat > "$HOOKS_DIR/post-commit" << 'EOF'
#!/bin/bash
# Auto-generated by scripts/setup-git-hooks.sh
# Pushes to GitHub after every commit (including Replit checkpoints).

bash "$(git rev-parse --show-toplevel)/scripts/github-sync.sh" &
EOF

chmod +x "$HOOKS_DIR/post-commit"
echo "[setup-git-hooks] post-commit hook installed at ${HOOKS_DIR}/post-commit"
